backend:
  name: git-gateway
  repo: zzrez/3qd-demo2

media_folder: src/images
public_folder: images

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }