backend:
  name: git-gateway
  repo: zzrez/3qd-demo2

media_folder: src/images
public_folder: images

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: "author", label: "Author", widget: "string", required: false }
      - { name: "poster", label: "Poster", widget: "string", required: false }
      - { name: "summary", label: "Summary", widget: "markdown", required: false }
      - {
        name: 'status',
        label: 'Status',
        widget: 'select',
        options: ['Published', 'Featured', 'Draft'],
        default: 'Published',
        }
      - { name: "externalSource", label: "Media Source", widget: "string", required: false }
      - { name: "externalUrl", label: "Media URL", widget: "string", required: false }
      - {
          name: "featuredImage",
          label: "Featured Image",
          widget: "image",
          required: false,
        }